<?php
$params = $this->getParams();

$pessoas = $params['pessoas'];
?>
<h2><?php echo $params['titulo']?></h2>
<table width="100%">
	<tr>
		<th>ID</th>
		<th>NOME</th>
		<th>EMAIL</th>
	</tr>
<?php foreach ($pessoas as $pessoa) : ?>
	<tr>
		<td><?php echo $pessoa['id']; ?></td>
		<td><?php echo $pessoa['nome']; ?></td>
		<td><?php echo $pessoa['email']; ?></td>
	</tr>
<?php endforeach; ?>
</table>